version: '3.8'

services:
  sptrescue:
    image: ghcr.io/ceraia/sptrescue:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    restart: unless-stopped
